### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by supers0nic98** [supers0nic98/gaming_central#1]
Welcome to the server!! we talk about anything gaming or sonic related.

**Comment by SuperMario201** [comment]
Noice! I reccomend putting stuff related to games in the repository

**Comment by supers0nic98** [comment]
I found this handy dandy site for sonic games its allsonicgames.net

**Comment by SuperMario201** [comment]
ah yes emulation has sure grown. Its reccomended you buy the real games to support SEGA
